### ISSUE TITLE
regession with 9a21e267c152f9c1a5848635694c4d35948be3bb: Enable more permissive issue identifier

### ISSUE THREAD

**Issue by vingu-linaro** [Linaro/jipdate#11]
Hi Joakim,

It looks like commit 9a21e267c152f9c1a5848635694c4d35948be3bb does the opposite of its commit message and is now less permissive than before 

commit c770fdabd0a3a284cb67d607543bfbfc7664c1f0 has already enable more permissive identifier. It enables [everything is allowed] but you have now restricted it to [XYZ-123 : This is my update]

You should revert 9a21e267c152f9c1a5848635694c4d35948be3bb

Vincent

**Comment by jbech-linaro** [comment]
Hi,

Oh, my patches was implementing a feature Mark Brown asked for and I didn't think about trying `[this should also work]` since I never use that myself. I can see that Christoffer added some pull request I haven't looked at the changes yet, so I cannot say whether that resolved this or not. But I will fix this in one or another way.

**Comment by chazy** [comment]
I don't fully follow the commits in the issue text, but I've just updated the pull request, and I'm pretty sure it solves this issue now.

**Comment by jbech-linaro** [comment]
@vingu-linaro , based on the reply from @chazy , can you check whether the issue you were facing was fixed or not (his patches are merged). I do believe it fixes it, I even tried a [foobar] section myself and that works. If all good, then I'd like to close this issue.

**Comment by vingu-linaro** [comment]
yes, issue has been fixed
