### ISSUE TITLE
jipdate asks for username even if -u option given

### ISSUE THREAD

**Issue by pm215** [Linaro/jipdate#14]
jipdate seems to prompt for a username even if I specified it with the -u option:

```
$ ./jipdate.py -t -u peter.maydell -q -f /tmp/status.txt
Username (john.doe@foo.org):
```

**Comment by jbech-linaro** [comment]
Yes and no ...
As a pre-condition to use Jira we need to login in with our **own** credentials. I.e, there is no ability to query our Jira server without providing your own login credentials. So, if you haven't given your username (and password) either by
* `export JIRA_USERNAME=peter.maydell@linaro.org`
* `username: peter.maydell@linaro.org` in the `config.yml`

then the final fallback is to ask for the credentials on command line instead and that is what you've been facing when trying the command line above.

By the way, `-u` is not necessary if you are just interested in issues assigned to yourself. I added `-u` to be able get issues assigned to other engineers in my team.

**Comment by pm215** [comment]
I understand that I need to give a username, but I've done that on the command line with -u, so I don't understand why it's asking me for a username on stdin as well -- it should use the one I said it should use, surely?

**Comment by jbech-linaro** [comment]
Ah, I understand what you are saying and indeed `-u` seems to be something that could be used as yet another alternative to the already existing ways of providing credentials. But here it is supposed to be used to query Jira with another username. Adding `-u` to the login procedure would remove the ability to query Jira for other users than yourself. But I do agree, it's quite common to see `-u` (username) and in some cases `-p` for password. Since you raised the issue here, I'm pretty sure others also will have the same issue/question. I'll see how I can change this to make it more easy to grasp.

**Comment by pm215** [comment]
Ah, I see. Yes, clarifying the documentation would be helpful here.
