### ISSUE TITLE
ASCII codec can't deal with accents

### ISSUE THREAD

**Issue by mrchapp** [Linaro/jipdate#23]
I have a wrong name to use with jipdate, it seems:
```
$ ./jipdate.py -q
Password: 
Traceback (most recent call last):
  File "./jipdate.py", line 458, in <module>
    main(sys.argv)
  File "./jipdate.py", line 442, in main
    filename = get_jira_issues(jira, username)
  File "./jipdate.py", line 213, in get_jira_issues
    f.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 62: ordinal not in range(128)
```
Issue might lie in my last name: Díaz. It can also be any other thing, though, as I do have a tendency to throw in some accents left and right in my cards.

**Comment by jbech-linaro** [comment]
Daniel, I'm pretty sure you are right here. I've seen that in other places too. I think the proper solution is to use UTF-8 formatted strings/functions. I'll see if I can come up with something (hopefully not to far in the future from now).

**Comment by jbech-linaro** [comment]
Hi Daniel,

I was about to test this and see if I could come up with a solution, but I'm having issue reproduce it on my side.
```bash
./jipdate.py -t -q -u daniel.diaz
```
That seems to be working, note that this is a normal 'i', not 'í', it gives me a list "KV-27: LKFT: GPIO tests are currently broken" (not this is the test server I'm querying). Do you enter your last name with the 'í' when logging into Jira? Or do you use a plain 'i'?

On the other hand if I enter
```bash
./jipdate.py -t -q -u daniel.díaz
```
Then I get no Jira issues in return, but I don't see the UnicodeEncodeError above. I can eventually dry-code a fix, but then I will probably need your help testing it out since I haven't figured out how to reproduce this.

**Comment by mrchapp** [comment]
Ok, I see what's going on. (FWIW, `./jipdate.py -t -q -u daniel.diaz` fails the same way.)

@danrue has shared a patch that converts the script from Python2 to Python3, and that seems to work! It's worked for me for the first time, and now I get an editor with a default message (from ~/.config/jipdate/.jipdate.yml) which DOES have an accent in the header section. I believe that you can then reproduce by adding any non-ASCII character to that section and then running a query.

I hope Dan will submit his patch shortly, which also helps in this case.
