### ISSUE TITLE
Querying for another user triggers captcha verification always

### ISSUE THREAD

**Issue by ibiris** [Linaro/jipdate#24]
I am trying to query the status of the stories assigned to another user. So based on the readme information I am running the following command

```
$> python jipdate.py -q -u firstname.lastname@linaro.org -v
Using config file: $HOME/.config/jipdate/.jipdate.yml
No user name found in JIRA_USERNAME environment variable
Forgot to export JIRA_PASSWORD?
Password: 
WARNING:root:Got recoverable error from GET https://projects.linaro.org/rest/api/2/serverInfo, will retry [1/3] in 12.2820254916s. Err: 401 
Captcha verification has been triggered by JIRA - please go to JIRA using your web browser, log out of JIRA, log back in entering the captcha; after that is done, please re-run the script
```

This captcha verification is triggered every time. 

If I try to run the command a second time without going through the captcha verification I get

```
$> python jipdate.py -q -u firstname.lastname@linaro.org -v 
Using config file: $HOME/.config/jipdate/.jipdate.yml
No user name found in JIRA_USERNAME environment variable
Forgot to export JIRA_PASSWORD?
Password: 
Captcha verification has been triggered by JIRA - please go to JIRA using your web browser, log out of JIRA, log back in entering the captcha; after that is done, please re-run the script
```
(so everything the same without the WARNING). 

In both cases there is no status output.

**Comment by ibiris** [comment]
My python version reads
```
Python 2.7.15rc1
```

I am running this on an Ubuntu 18.04

**Comment by jbech-linaro** [comment]
Hi Ilias, we're running same OS version and everything and also same Python version, which is good! :) I was running a couple of tests here on my side and I don't even get the captcha warning. Probably because I have a valid session already ongoing. How the Jira plugin in Python deals with that is something I've been unable to figure out, which makes problems like yours hard to debug (since I'm not always able to reproduce the error, like now). Anyhow, I'll try to see what I can come up with. For now thanks for reporting the issue.

Unrelated but that caught my attention in your output is the messages about `JIRA_USERNAME` and `JIRA_PASSWORD` when running with verbose. That seems like a bug.

**Comment by ibiris** [comment]
I have the user name in the jipdate.yml so that is a bug for sure. But the password may be just an info message, I do not want my password stored in a file or variable so I enter it manually every time when prompted.

**Comment by ibiris** [comment]
Also related to your comment about a valid session. Every time I was prompted for a reverification I logged out of JIRA on my browser and logged back in again (passing through the captcha verification as well). So I had a valid session every time I tried the tool.
