### ISSUE TITLE
Jipdate fails after April 7th changes

### ISSUE THREAD

**Issue by maxim-kuvyrkov** [Linaro/jipdate#35]
TCWG CI uses jipdate master branch to add comments to jira about regressions detected in various components.  Jipdate started to fail this morning with:
`UnboundLocalError: local variable 'issues' referenced before assignment`
Full log is at https://ci.linaro.org/view/tcwg_kernel-gnu/job/tcwg_kernel-bisect-llvm-master-arm-next-allmodconfig/73/console .

The problem occurred between April 3 and April 8, this range only has 4 commits from @ndechesne .
@ndechesne , would you please investigate?

To reproduce the problem this should be enough:
```
cat > jira-body.txt <<EOF
[GNU-587]
Test comment
EOF
export JIRA_USERNAME=$USER
export JIRA_PASSWORD=$PASSWORD
export EDITOR=cat
echo y | jipdate.py -f jira-body.txt
```

**Comment by ndechesne** [comment]
ouch. sorry. I understand what the problem is.. it's in 49866d087fcc53b3ba169f97b545437faf2eee85. It is an optimization to avoid refetching the issues that we got from the query. However when you use a file we don't have an initial query. It manifests with the variable not defined, but the actual problem is bigger than that.. 

So we need to update the patch, and probably check if the issue has been fetched already, and if not then query. 

I am ok to revert this patch for now if that helps everyone, and i will resubmit a better version. or i can try to have a fix up patch on top.. either way, i really want to get the optimization..

**Comment by jbech-linaro** [comment]
> I am ok to revert this patch for now if that helps everyone

Send a revert PR and I'll merge it.

**Comment by ndechesne** [comment]
that should fix the issue. if you can give it a try, that would be good.

**Comment by jbech-linaro** [comment]
@maxim-kuvyrkov , can you give it a try to see whether #36 fixes the issue?

**Comment by maxim-kuvyrkov** [comment]
Testing.  This will take some hours, since docker images need to be regenerated, and CI needs to pick that up.
